
server:
  port: 8092
spring:
    application:
        name: courses-service

eureka:
  client:
    fetch-registry: true
  instance:
    hostname: EUREKA_HOST  

services:
    studants:
        url: STUDANTS-SERVICE